//
// Created by song on 9/19/18.
//


#include "include/gtest/gtest.h"
#include "../seed.h"
#include "../fasta.h"
#include "../Score.h"
#include "../gffToCategory.h"
#include <string>
#include <iostream>
#include <sstream>

TEST(seed, c1){
     std::string seqA="ATGGCGAATCTCCAGAGGGAGAGGAACCCAAGGTTGTGGCTCATAGAGAAGATATAAAGGCGCAGTTCAAGGCCGCACAACAGGTGGCGAAACCTCGTGCTCATTGGCCTCCAGAGGCCGCAAAAGCTTTCAGTGAAATATGCATTGAGAAAAGGGATTTAATCCCTTCAGGAAAAGCTAATAGTTGGGTTGGACACCCTATATCTGATGAAGTTGGATTAGAGCTTTTTCTTCTGACAAATATAGCCTACACAAGTAAACAGATGGGAAACAAGTGGTGCAACATGAGAGAATTACAACATAAAAAAGACTTGATACAAACAAGAATGTTTGATGAGCCCCACTCAGCTGCCGGGCACCTCAGACTGCCAGGACAAGAGGAAAATGAAAGTGTGAAATATCTTAAGCTAGAAGAAGAGAATGCCCGATTAAATAAACAACTGCAGGAAACGTTGACAAAAGTTAACCATCTTCAAGATCTACTTCAAAAAGCAGATGCAATACGTAGCACAATGCATAATCAAATAATGGAACTGAAGAAAAGCATACGTGTGTTTTGCCGTGTGCGACCATTGCTACAAACAGAACACAAACAGGCCAGAATCACATTTCCTGAAACATGGGGATACATTGGCCGATGTGTTTGTTTGGCACATTCAGAGTCAGAATATTCTTTCACCTGTGATAGAGTCTTTGACCATACAGCTTCACAAGAAACAATATTCAATGAAATTTCAGAATTAGTGCAGAGTGCACTTGATGGACACAAGGTGTGCATATTTGCTTATGGTCAAACCGGTTCCGGTAAGACCTACACCATGATTGGTGAGAGAGAAGGGGATGACATGGGGATAATTCCTCGCACACTTGCGAAAATATTTGAGACCATTGAAATTCGACAATCTTATGGCTCAAATCACACCGTAATGATTTCAATGTTTGAGGTTTATAATGACAAAGTTCAAGATTTATTATCCCCATTGGCACACAATGATGACTTGCAATATGTTGTTGTTAAAACAGCAACTGAGGCACTTGGATATTTGGAGAAATCATTGAAAAAGAGGTCTGTTGCCAGAACTAAACTGAATGATAGATCATCGCGAAGCCACTTTATTTTTAAGCTGTCCATATGTTCCACTGATAAGATGCTTGAAGGGGTTGTCAACATTATCGACTTAGCTGGTAGTGAACGCCCCGACAGTGATGCGTCACGTGACCTTCAAGAGGAGGCCAAGGCCATAAATTTAAGTCTACTCGATTTGGGCATTGTCCTTTCAAAAATGGAGAATGGAGAAAATAATATATCATTTAGAGGATCGACTCTGTCTCAAATTTTAGAGAGATCACTTGGAAAAGATTTTAAAACATTAATGTTGCTTAATGTTGCATCGGAAGAAAAGTTTGCTTCTGAAACATTAGCAACATTTGATTTTGCTTCGAGGATAAAATCATGCAAAAAGACAATGAGGATAATAAAAGCTAATGAACAGAAGATTGTGTTAAGAGGAAAGGAAGGATTCAAATCGCCAGGGGGTTGGCATGAAAAAGGCGGACCGTGCATAAAGTCTCCATCTATAGCAAGGAATACAAGAAAGAAAGTTATGAGCACTGCAAATAGGCAAGGAGACTATAATAGAAAGAGGAAGATGTATCCTAACGATTGA";
     std::string seqB="ATGGCGAATCTCCAGAGAGGAGAGGAACCCAAGGTTGTGGCTCATAGAGAAGATATAAAGGCGCAGTTCAAGGCCGCACAACAGGTGGCGAAACCTCGTGCTCATTGGCCTCCAGAGGCCGCAAAAGCTTTCAGTGAAATATGCATTGAGAAAAGGGATTTAATCCCTTCAGGAAAAGCTAATAGTTGGGTTGGACACCCTATATCTGATGAAGTTGGATTAGAGCTTTTTCTTCTGACAAATATAGCCTACACAAGTAAACAGATGGGAAACAAGTGGTGCAACATGAGAGAATTACAACATAAAAAAGACTTGATACAAACAAGAATGTTTGATGAGCCCCACTCAGCTGCCGGGCACCTCAGACTGCCAGGACAAGAGGAAAATGAAAGTGTGAAATATCTTAAGCTAGAAGAAGAGAATGCCCGATTAAATAAACAACTGCAGGAAACGTTGACAAAAGTTAACCATCTTCAAGATCTACTTCAAAAAGCAGATGCAATACGTAGCACAATGCATAATCAAATAATGGAACTGAAGAAAAGCATACGTGTGTTTTGCCGTGTGCGACCATTGCTACAAACAGAACACAAACAGGCCAGAATCACATTTCCTGAAACATGGGGATACATTGGCCGATGTGTTTGTTTGGCACATTCAGAGTCAGAATATTCTTTCACCTGTGATAGAGTCTTTGACCATACAGCTTCACAAGAAACAATATTCAATGAAATTTCAGAATTAGTGCAGAGTGCACTTGATGGACACAAGGTGTGCATATTTGCTTATGGTCAAACCGGTTCCGGTAAGACCTACACCATGATTGGTGAGAGAGAAGGGGATGACATGGGGATAATTCCTCGCACACTTGCGAAAATATTTGAGACCATTGAAATTCGACAATCTTATGGCTCAAATCACACCGTAATGATTTCAATGTTTGAGGTTTATAATGACAAAGTTCAAGATTTATTATCCCCATTGGCACACAATGATGACTTGCAATATGTTGTTGTTAAAACAGCAACTGAGGCACTTGGATATTTGGAGAAATCATTGAAAAAGAGGTCTGTTGCCAGAACTAAACTGAATGATAGATCATCGCGAAGCCACTTTATTTTTAAGCTGTCCATATGTTCCACTGATAAGATGCTTGAAGGGGTTGTCAACATTATCGACTTAGCTGGTAGTGAACGCCCCGACAGTGATGCGTCACGTGACCTTCAAGAGGAGGCCAAGGCCATAAATTTAAGTCTACTCGATTTGGGCATTGTCCTTTCAAAAATGGAGAATGGAGAAAATAATATATCATTTAGAGGATCGACTCTGTCTCAAATTTTAGAGAGATCACTTGGAAAAGATTTTAAAACATTAATGTTGCTTAATGTTGCATCGGAAGAAAAGTTTGCTTCTGAAACATTAGCAACATTTGATTTTGCTTCGAGGATAAAATCATGCAAAAAGACAATGAGGATAATAAAAGCTAATGAACAGAAGATTGTGTTAAGAGGAAAGGAAGGATTCAAATCGCCAGGGGGTTGGCATGAAAAAGGCGGACCGTGCATAAAGTCTCCATCTATAGCAAGGAATACAAGAAAGAAAGTTATGAGCACTGCAAATAGGCAAGGAGACTATAATAGAAAGAGGAAGATGTATCCTAACGATTGA";

//    std::string seqA="ATGGCGAATCTCCAGAGGGAGAGGAA";
//    std::string seqB="ATGGCGAATCCCAGAGGGAGAGGAA";

    /*currently this code should work for chromosome with length ~2g and does not work for longer one
     *
     * */

    std::map<std::string, std::string> b73;
    readFastaFile( "/Users/bs674/b73.fa",  b73);

    std::map<std::string, std::string> mo17;
    readFastaFile( "/Users/bs674/Mo17.fa",  mo17);

    // the initialSeedLength and initialSeedsScoreThreadsHold value was set basing the default score parameter of minimap2 match:2 mismatch:-4 opengap:-4 extendgap:-2
    // in a 8 match alignment there could be one indel in the middle, so we set initialSeedLength as 7
    // in a 7 bp alignment only one mismatch is possiable

    int lengthWantTouse=100000;
    int16_t category[100000] ={ 0 };
    int8_t initialSeedLength=7;
    int8_t initialSeedsScoreThreadsHold=6;

    Score score("/Users/bs674/scoreMatrix");
    seq2seed ( b73["1"].substr(0, lengthWantTouse),  mo17["1"].substr(0, lengthWantTouse), category, initialSeedLength, initialSeedsScoreThreadsHold, 12, score);


//    const char * seqAChar = seqA.c_str();
//    const char * seqBChar = seqB.c_str();
//    zdp(seqAChar, seqBChar, 10, 15, category, score);

    ASSERT_EQ(0, 0);
}

TEST(gffToCategory, c1){
    std::map<std::string, std::string> b73;
    readFastaFile( "/Users/bs674/Zea_mays.B73_RefGen_v4.dna.toplevel.fa",  b73);
    std::map<std::string, int32_t> chrSize;
    for( std::map<std::string, std::string>::iterator it=b73.begin(); it != b73.end(); ++it){
        chrSize[it->first] = it->second.size();
    }

    std::string gffFile = "/Users/bs674/Zea_mays.B73_RefGen_v4.42.gff3";
    std::string outputFile = "/Users/bs674/category";
    readGffFileWithEveryThing (gffFile,  chrSize, outputFile);
}

TEST(seed, c2){
    std::map<std::string, std::string> b73;
    readFastaFile( "/Users/bs674/b73.fa",  b73);

    std::map<std::string, std::string> mo17;
    readFastaFile( "/Users/bs674/Mo17.fa",  mo17);

    std::map<std::string, int16_t *> weight;
    charByCharCategoryRead( "/Users/bs674/category", mo17,  weight );

    int lengthWantTouse=100000;

    int8_t initialSeedLength=7;
    int8_t initialSeedsScoreThreadsHold=6;

    Score score("/Users/bs674/scoreMatrix");
    seq2seed ( b73["1"].substr(0, lengthWantTouse),  mo17["1"].substr(0, lengthWantTouse), weight[0], initialSeedLength, initialSeedsScoreThreadsHold, 12, score);

    for( std::map<std::string, int16_t *>::iterator it=weight.begin(); it != weight.end(); ++it ){
        delete[] it->second;
    }
    ASSERT_EQ(0, 0);
}
